### ISSUE TITLE
Prevent sanitizing some fields (feature request)

### ISSUE THREAD

**Issue by miadabdi** [jsonmaur/xss-clean#1]
I am using this package as a middleware in Express and it works fine, but I am also using EditorJs as my rich text editor in front-end. My problem is that EditorJs generates an object which there is html in it, and I don't want to sanitize the incoming object of EditorJs. So I am asking if there is a way to exclude some fields (in my case it is "req.body.editorObj") from sanitizing process?

**Comment by jsonmaur** [comment]
Hi @MichaelMikeJones, no it doesn't support that. I don't really use or maintain this library anymore & I'm surprised to hear someone is using it. Would be happy to accept a PR if you want to give it a go.

**Comment by nvispute** [comment]
I too am looking for Somthing similar.

**Comment by miadabdi** [comment]
@nvispute I couldn't find anything like that but I did this:
```javascript
// save the data out of req.body
app.use((req, res, next) => {
    if (req.body.body) req.EditorJsBody = {...req.body.body };
    next();
});

app.use(xss());

// restore the data
app.use((req, res, next) => {
    if (req.EditorJsBody) req.body.body = req.EditorJsBody;
    next();
});
```
And to be honest, I don't know if this is safe.

**Comment by nvispute** [comment]
@MichaelMikeJones i am using Quilljs and what i found is that the package is converting the HTML tags inside the field to HTML Entities.. here is a small sinnpet
```
"&lt;h1 class=\"ql-align-center\">Essential things to think about before starting a blog&lt;/h1>&lt;p>&lt;br>&lt;/p>&lt;h2 class=\"ql-align-center\">​It takes several ingredients to create a delicious blog&lt;/h2>&lt;p>&lt;br>&lt;/p>&lt;p class=\"ql-align-justify\">It has been exactly 3 years since I wrote my first blog series entitled “Flavorful Tuscany”, but starting it was definitely not easy. Back then, I didn’t know much about blogging, let alone think that one day it could become &lt;strong>my full-time job&lt;/strong>. Even though I had many recipes and food-related stories to tell, it never crossed my mind that I could be sharing them with the whole world.&lt;/p>&lt;p class=\"ql-align-justify\">I am now a &lt;strong>full-time blogger&lt;/strong> and the curator of the &lt;a href=\"https://ckeditor.com/ckeditor-4/#\" target=\"_blank\">Simply delicious newsletter&lt;/a>, sharing stories about traveling and cooking, as well as tips on how to run a successful blog.&lt;/p>&lt;p class=\"ql-align-justify\">If you are tempted by the idea of creating your own blog, please think about the
    following:&lt;/p>&lt;ul>&lt;li class=\"ql-align-justify\">Your story
    (what do you want to tell your audience)&lt;/li>&lt;li class=\"ql-align-justify\">Your audience (who do you write for)&lt;/li>&lt;li class=\"ql-align-justify\">Your blog name and design&lt;/li>&lt;/ul>"
```

Notice how the `'<'` are converted to `'&lt;'` on all the HTML tags, so as a solution i handled this covertion inside the controller without touching the original data stream. 
Step1: reverted the `"&lt;"` to `"<"` [This made the tag whole something like this` ("<h1 class=\"ql-align-center\">)` ]
Step2: Removed the additional `' \'` inside the tag using the Set() on the array Html objects . 
Step 3: rebuild the data stream and saved it db.
