### ISSUE TITLE
xss-clean 0.1.2 and 0.1.3 are broken

### ISSUE THREAD

**Issue by lorand-horvath** [jsonmaur/xss-clean#6]
@jsonmaur I'm contacting you here because I can't reach you on the now archived repo https://github.com/jsonmaur/xss-clean

I've just installed the latest xss-clean 0.1.3 and when I start my app, it doesn't find the lib folder in node_modules/xss-clean
Checked and I can only see package.json and README.md so there must have happened something wrong with the build process.

It would be good to un-archive it until these kinds of issues are ironed out.
I have reverted to the 7-year old 0.1.1 for the moment.

Thanks and sorry for opening an issue in this unrelated repo!

**Comment by jsonmaur** [comment]
Thanks for letting me know, I just saw your email. Not sure what happened there... I republished under 0.1.4, see if that fixes it. I really don't do much in the JS ecosystem these days and don't have time to maintain this library, hence the deprecation today. But I definitely don't want it to break stuff.

**Comment by lorand-horvath** [comment]
0.1.4 works fine, thanks! I think the issue was that 0.1.2 and 0.1.3 were published as deprecated on https://www.npmjs.com/package/xss-clean?activeTab=versions and for some reason the lib directory was missing when installing.

**Comment by jsonmaur** [comment]
Seems like the prepublish script didn’t run like it should’ve when I published from a fresh clone. And I just didn’t look closely at the files being uploaded. Sorry about that!
